export { default as Navbar } from "./Navbar/Navbar";
export { default as Footer } from "./Footer/Footer";
export { default as Home } from "./Home/Home";
export { default as HomeRegister } from "./Home/HomeRegister";
export { default as Contact } from "./Home/Contact";
export { default as Balance } from "./UserDashboard/Balance";
export { default as Traiding } from "./UserDashboard/Traiding";
export { default as Transactions } from "./UserDashboard/Transactions";
export { default as CoinList } from "./Market/CoinList";
